sample : sample.cpp ../dbcompress.o
	g++ -std=c++11 -O3 -Wall ../dbcompress.o sample.cpp -o sample

corel : corel.cpp corel.h corel_model.cpp ../dbcompress.o
	g++ -std=c++11 -O3 -Wall ../dbcompress.o corel.cpp corel_model.cpp -o corel
